### ISSUE TITLE
Error in Windows 11

### ISSUE THREAD

**Issue by Someone112113** [MarconiGRF/YTGameBarOverlay#13]
Hi, there is a problem when using this app in windows 11. The video will pause, or sometimes the app will crash when I exit the gamebar.
Video: https://drive.google.com/file/d/11Exp09sCaF1ykb-nBBOPesXmRPtzn37R/view?usp=sharing
(The sound is a bit low, so please turn the volume up)

**Comment by MarconiGRF** [comment]
Hello, unfortunately Game Bar SDK changed internally about the background activity of widgets. Although YTGBO is still running at the background (you can see by the video time still counting) it has its audio output suppressed by Windows itself.

For this reason the fix for this bug is beyond my control, sorry.
You can still pin the widget to the Game Bar and it will work as expected.
