### ISSUE TITLE
copy pasting link not working 

### ISSUE THREAD

**Issue by K-ashvi** [MarconiGRF/YTGameBarOverlay#17]
neither pasting a link nor searching is working. Shows error : Video not available. 
Only history works.

**Comment by MarconiGRF** [comment]
Hi @K-ashvi , can you provide the link used when the issue happened?

**Comment by K-ashvi** [comment]
these are some of the ones i've tried:
https://youtu.be/_9Z05Ik5r2U?si=3valnAFJ5zgLGJUS
https://youtu.be/Tx5e5e2vKS0?si=FWCChWlBr96G-l1e
https://youtu.be/O5DhgK9D9ko?si=UKCA4BzVn0meMfSD

**Comment by MarconiGRF** [comment]
I understand, unfortunately due to the parsing capabilities of the app the only formats that are accepted arein the form of "youtube.com/watch?v=.....". I confirmed that the provided videos with this URL format are accepted and work as usual.

Due to the complexity of the project and other external API dependencies I won't be implementing the parsing for this URL format. For more info please refer to the README to read the deprecation notice.
